language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
before_install:
  - sudo apt-get install --assume-yes libmysql++-dev
  - sudo apt-get install --assume-yes postgresql-server-dev-9.1
  - gem update --system
  - curl -O http://fs-packages.s3.amazonaws.com/fs-sphinx-2.0.6_i386_12.04.deb
  - sudo dpkg -i fs-sphinx-2.0.6_i386_12.04.deb
before_script:
  - "mysql -e 'create database thinking_sphinx;' > /dev/null"
  - "psql -c 'create database thinking_sphinx;' -U postgres >/dev/null"
env:
  - DATABASE=mysql2 SPHINX_BIN=/usr/local/sphinx-2.0.6/bin/ SPHINX_VERSION=2.0.6
  - DATABASE=postgresql SPHINX_BIN=/usr/local/sphinx-2.0.6/bin/ SPHINX_VERSION=2.0.6
gemfile:
  - gemfiles/rails_3_1.gemfile
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile
