rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - rbx-2.0
  - ree
before_script:
  - "mysql -e 'create database thinking_sphinx;' > /dev/null"
  - "psql -c 'create database thinking_sphinx;' -U postgres >/dev/null"
env:
  - DATABASE=mysql2
  - DATABASE=postgresql
